/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.pruebafiguras;

/**
 *
 * @author 1
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtCRadio = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtCArea = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtCPerimetro = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnArea = new javax.swing.JButton();
        btnPerimetro = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        btnBorrarCu = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtCuLado = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtCuArea = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtCuPerimetro = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        btnAreaCu = new javax.swing.JButton();
        btnPerimetroCu = new javax.swing.JButton();
        btnBorrarRec = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txtReBase = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtReAltura = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtReArea = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        btnAreaRec = new javax.swing.JButton();
        btnPerimetroRec = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        txtRePerimetro = new javax.swing.JTextField();
        btnBorrarTR = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        txtTRBase = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtTRAltura = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtTRArea = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        btnAreaTR = new javax.swing.JButton();
        btnPerimetroTR = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        txtTRPerimetro = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtTRHipotenusa = new javax.swing.JTextField();
        btnHipotenusa = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Radio");

        jLabel2.setText("Área");

        jLabel3.setText("Perímetro");

        txtCPerimetro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCPerimetroActionPerformed(evt);
            }
        });

        jLabel4.setText("Círculo");

        btnArea.setText("Calcular Área");
        btnArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAreaActionPerformed(evt);
            }
        });

        btnPerimetro.setText("Calcular Perímetro");
        btnPerimetro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPerimetroActionPerformed(evt);
            }
        });

        btnBorrar.setText("Borrar");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });

        btnBorrarCu.setText("Borrar");
        btnBorrarCu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarCuActionPerformed(evt);
            }
        });

        jLabel5.setText("Lado");

        txtCuLado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCuLadoActionPerformed(evt);
            }
        });

        jLabel6.setText("Área");

        jLabel7.setText("Perímetro");

        txtCuPerimetro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCuPerimetroActionPerformed(evt);
            }
        });

        jLabel8.setText("Cuadrado");

        btnAreaCu.setText("Calcular Área");
        btnAreaCu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAreaCuActionPerformed(evt);
            }
        });

        btnPerimetroCu.setText("Calcular Perímetro");
        btnPerimetroCu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPerimetroCuActionPerformed(evt);
            }
        });

        btnBorrarRec.setText("Borrar");
        btnBorrarRec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarRecActionPerformed(evt);
            }
        });

        jLabel9.setText("Base");

        txtReBase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtReBaseActionPerformed(evt);
            }
        });

        jLabel10.setText("Altura");

        jLabel11.setText("Área");

        txtReArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtReAreaActionPerformed(evt);
            }
        });

        jLabel12.setText("Rectángulo");

        btnAreaRec.setText("Calcular Área");
        btnAreaRec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAreaRecActionPerformed(evt);
            }
        });

        btnPerimetroRec.setText("Calcular Perímetro");
        btnPerimetroRec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPerimetroRecActionPerformed(evt);
            }
        });

        jLabel13.setText("Perímetro");

        txtRePerimetro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRePerimetroActionPerformed(evt);
            }
        });

        btnBorrarTR.setText("Borrar");
        btnBorrarTR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarTRActionPerformed(evt);
            }
        });

        jLabel14.setText("Base");

        txtTRBase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTRBaseActionPerformed(evt);
            }
        });

        jLabel15.setText("Altura");

        jLabel16.setText("Área");

        txtTRArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTRAreaActionPerformed(evt);
            }
        });

        jLabel17.setText("Triangulo Rectángulo");

        btnAreaTR.setText("Calcular Área");
        btnAreaTR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAreaTRActionPerformed(evt);
            }
        });

        btnPerimetroTR.setText("Calcular Perímetro");
        btnPerimetroTR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPerimetroTRActionPerformed(evt);
            }
        });

        jLabel18.setText("Perímetro");

        txtTRPerimetro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTRPerimetroActionPerformed(evt);
            }
        });

        jLabel19.setText("Hipotenusa");

        txtTRHipotenusa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTRHipotenusaActionPerformed(evt);
            }
        });

        btnHipotenusa.setText("Calcular Hipotenusa");
        btnHipotenusa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHipotenusaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(16, 16, 16)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(38, 38, 38)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtCRadio)
                                        .addComponent(txtCArea)
                                        .addComponent(txtCPerimetro))
                                    .addGap(26, 26, 26))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(125, 125, 125)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGap(149, 149, 149))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(btnAreaRec)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(btnPerimetroRec)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(btnBorrarRec))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(btnArea)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(btnPerimetro)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(btnBorrar)))
                                    .addGap(0, 0, Short.MAX_VALUE))))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(131, 131, 131)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGap(125, 125, 125)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtReAltura, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtReArea, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtRePerimetro, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtReBase, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(112, 112, 112)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAreaCu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnPerimetroCu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBorrarCu))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(5, 5, 5)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCuLado)
                                    .addComponent(txtCuArea)
                                    .addComponent(txtCuPerimetro)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(125, 125, 125)
                                        .addComponent(jLabel8))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(24, 24, 24)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtTRBase, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtTRAltura, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtTRArea, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtTRPerimetro, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtTRHipotenusa, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(49, 49, 49))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(btnHipotenusa)
                        .addGap(153, 153, 153))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnAreaTR)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnPerimetroTR)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBorrarTR)
                                .addGap(75, 75, 75))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(180, 180, 180))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel4)
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3)
                                .addGap(23, 23, 23)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnArea)
                                    .addComponent(btnPerimetro)
                                    .addComponent(btnBorrar)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtCRadio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtCArea, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtCPerimetro, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8)
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel7))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtCuLado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtCuArea, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtCuPerimetro, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAreaCu)
                            .addComponent(btnPerimetroCu)
                            .addComponent(btnBorrarCu))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel11)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel13))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtReBase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtReAltura, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtReArea, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtRePerimetro, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAreaRec)
                            .addComponent(btnPerimetroRec)
                            .addComponent(btnBorrarRec)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel15)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel16)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel18)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel19))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtTRBase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtTRAltura, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtTRArea, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtTRPerimetro, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtTRHipotenusa, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAreaTR)
                    .addComponent(btnPerimetroTR)
                    .addComponent(btnBorrarTR))
                .addGap(18, 18, 18)
                .addComponent(btnHipotenusa)
                .addGap(45, 45, 45))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAreaActionPerformed
    
    double area; 
    int radio = Integer.parseInt(txtCRadio.getText());
    Circulo figura1 = new Circulo(radio);
    area = figura1.calcularArea();
    txtCArea.setText(String.valueOf(area));
    
    }//GEN-LAST:event_btnAreaActionPerformed

    private void btnPerimetroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPerimetroActionPerformed
    double perimetro; 
    int radio = Integer.parseInt(txtCRadio.getText());
    Circulo figura1 = new Circulo(radio);
    perimetro = figura1.calcularPerimetro();
    txtCPerimetro.setText(String.valueOf(perimetro));
    }//GEN-LAST:event_btnPerimetroActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
    
    txtCRadio.setText("");
    txtCArea.setText("");
    txtCPerimetro.setText("");
        
        
        
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void txtCPerimetroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCPerimetroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCPerimetroActionPerformed

    private void btnBorrarCuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarCuActionPerformed
    
    txtCuLado.setText("");
    txtCuArea.setText("");
    txtCuPerimetro.setText("");
        
    }//GEN-LAST:event_btnBorrarCuActionPerformed

    private void txtCuPerimetroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCuPerimetroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCuPerimetroActionPerformed

    private void btnAreaCuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAreaCuActionPerformed
    
    double area; 
    int lado = Integer.parseInt(txtCuLado.getText());
    Cuadrado figura3 = new Cuadrado(lado);
    area = figura3.calcularArea();
    txtCuArea.setText(String.valueOf(area));
    }//GEN-LAST:event_btnAreaCuActionPerformed

    private void btnPerimetroCuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPerimetroCuActionPerformed
    
    double perimetro; 
    int lado = Integer.parseInt(txtCuLado.getText());
    Cuadrado figura3 = new Cuadrado(lado);
    perimetro = figura3.calcularPerimetro();
    txtCuPerimetro.setText(String.valueOf(perimetro));
    }//GEN-LAST:event_btnPerimetroCuActionPerformed

    private void btnBorrarRecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarRecActionPerformed
   
    txtReBase.setText("");
    txtReAltura.setText("");
    txtRePerimetro.setText("");
    txtReArea.setText("");
        
    }//GEN-LAST:event_btnBorrarRecActionPerformed

    private void txtReAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtReAreaActionPerformed

    }//GEN-LAST:event_txtReAreaActionPerformed

    private void btnAreaRecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAreaRecActionPerformed
    
    double area;
    int base = Integer.parseInt(txtReBase.getText());
    int altura = Integer.parseInt(txtReAltura.getText());
    Rectangulo figura4 = new Rectangulo(base, altura);
    area = figura4.calcularArea();
    txtReArea.setText(String.valueOf(area));                                       
    }//GEN-LAST:event_btnAreaRecActionPerformed

    private void btnPerimetroRecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPerimetroRecActionPerformed
    double perimetro;
    int base = Integer.parseInt(txtReBase.getText());
    int altura = Integer.parseInt(txtReAltura.getText());
    Rectangulo figura4 = new Rectangulo(base, altura);
    perimetro = figura4.calcularPerimetro();
    txtRePerimetro.setText(String.valueOf(perimetro)); 
    }//GEN-LAST:event_btnPerimetroRecActionPerformed

    private void txtRePerimetroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRePerimetroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRePerimetroActionPerformed

    private void txtReBaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtReBaseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtReBaseActionPerformed

    private void txtCuLadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCuLadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCuLadoActionPerformed

    private void btnBorrarTRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarTRActionPerformed
    txtTRBase.setText("");
    txtTRAltura.setText("");
    txtTRPerimetro.setText("");
    txtTRArea.setText("");
    txtTRHipotenusa.setText("");
        
    }//GEN-LAST:event_btnBorrarTRActionPerformed

    private void txtTRBaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTRBaseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTRBaseActionPerformed

    private void txtTRAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTRAreaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTRAreaActionPerformed

    private void btnAreaTRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAreaTRActionPerformed
        // TODO add your handling code here:
        
    double area;
    int base = Integer.parseInt(txtTRBase.getText());
    int altura = Integer.parseInt(txtTRAltura.getText());
    TrianguloRectangulo figura5 = new TrianguloRectangulo(base, altura);
    area = figura5.calcularArea();
    txtTRArea.setText(String.valueOf(area));   
    
    }//GEN-LAST:event_btnAreaTRActionPerformed

    private void btnPerimetroTRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPerimetroTRActionPerformed
    double perimetro_triangulo_rectangulo; 
    int base_triangulo_rectangulo = Integer.parseInt(txtTRBase.getText());
    int altura_triangulo_rectangulo = Integer.parseInt(txtTRAltura.getText()); 
    TrianguloRectangulo figura5 = new TrianguloRectangulo(base_triangulo_rectangulo,altura_triangulo_rectangulo);
    perimetro_triangulo_rectangulo = figura5.calcularPerimetro(); 
    txtTRPerimetro.setText(String.valueOf(perimetro_triangulo_rectangulo));
    }//GEN-LAST:event_btnPerimetroTRActionPerformed

    private void txtTRPerimetroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTRPerimetroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTRPerimetroActionPerformed

    private void txtTRHipotenusaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTRHipotenusaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTRHipotenusaActionPerformed

    private void btnHipotenusaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHipotenusaActionPerformed
    double hipotenusa;
    int base = Integer.parseInt(txtTRBase.getText());
    int altura = Integer.parseInt(txtTRAltura.getText());
    TrianguloRectangulo figura5 = new TrianguloRectangulo(base, altura);
    hipotenusa = figura5.calcularHipotenusa();
    txtTRHipotenusa.setText(String.valueOf(hipotenusa)); 
        

    }//GEN-LAST:event_btnHipotenusaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnArea;
    private javax.swing.JButton btnAreaCu;
    private javax.swing.JButton btnAreaRec;
    private javax.swing.JButton btnAreaTR;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnBorrarCu;
    private javax.swing.JButton btnBorrarRec;
    private javax.swing.JButton btnBorrarTR;
    private javax.swing.JButton btnHipotenusa;
    private javax.swing.JButton btnPerimetro;
    private javax.swing.JButton btnPerimetroCu;
    private javax.swing.JButton btnPerimetroRec;
    private javax.swing.JButton btnPerimetroTR;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtCArea;
    private javax.swing.JTextField txtCPerimetro;
    private javax.swing.JTextField txtCRadio;
    private javax.swing.JTextField txtCuArea;
    private javax.swing.JTextField txtCuLado;
    private javax.swing.JTextField txtCuPerimetro;
    private javax.swing.JTextField txtReAltura;
    private javax.swing.JTextField txtReArea;
    private javax.swing.JTextField txtReBase;
    private javax.swing.JTextField txtRePerimetro;
    private javax.swing.JTextField txtTRAltura;
    private javax.swing.JTextField txtTRArea;
    private javax.swing.JTextField txtTRBase;
    private javax.swing.JTextField txtTRHipotenusa;
    private javax.swing.JTextField txtTRPerimetro;
    // End of variables declaration//GEN-END:variables
}
